services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    environment:
      ORACLE_PWD: password
      ORACLE_SID: FREE
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD", "sqlplus", "-s", "system/password@FREE", "SELECT 1 FROM dual;" ]
      interval: 10s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./lab4backend
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/FREE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  oracle-data:
