CREATE TABLE USERS(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE POINTS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    x NUMBER NOT NULL,
    y NUMBER NOT NULL,
    r NUMBER NOT NULL,
    hit NUMBER(1) NOT NULL CHECK ( hit IN (0, 1) ),
    userId NUMBER NOT NULL
)